//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISMyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnus()
        {
            this.AlumiModules = new HashSet<AlumiModule>();
        }
    
        public int SSN { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Current_Position { get; set; }
        public Nullable<decimal> Current_Salery { get; set; }
        public Nullable<decimal> GPA { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Graduated_ON { get; set; }
        public Nullable<int> School_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumiModule> AlumiModules { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual School School { get; set; }
    }
}
