//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISMyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumiModule
    {
        public int AlumiModule_ID { get; set; }
        public Nullable<int> Module_Code { get; set; }
        public Nullable<int> SSN { get; set; }
        public Nullable<bool> ResultStatus { get; set; }
    
        public virtual Alumnus Alumnus { get; set; }
        public virtual Module Module { get; set; }
    }
}
