//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISMyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Modules = new HashSet<Module>();
        }
    
        public int Course_Code { get; set; }
        public string Course_Name { get; set; }
        public string Course_Topic_Covered { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Curriculum_Code { get; set; }
        public Nullable<int> ICCSD_ID { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual ICCSD ICCSD { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Module> Modules { get; set; }
    }
}
