//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISMyWebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBASystemEntities : DbContext
    {
        public MBASystemEntities()
            : base("name=MBASystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumiModule> AlumiModules { get; set; }
        public virtual DbSet<Alumnus> Alumni { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Curriculum> Curricula { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ICCSD> ICCSDs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<RegisteredModule> RegisteredModules { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolCurriculum> SchoolCurriculums { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
