//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISMyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolCurriculum
    {
        public int SchoolCurriculum_ID { get; set; }
        public Nullable<int> Curriculum_Code { get; set; }
        public Nullable<int> School_ID { get; set; }
        public Nullable<int> Last_Updated { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual School School { get; set; }
    }
}
